name: site

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/__tests__/**'
  workflow_dispatch:

jobs:
  site:
    runs-on: ubuntu-latest

    env:
      DOCS_GA_ID: G-CTB8FQ7VMW
      DOCS_BA_ID: 2bec8aabb0629582fd66244ae851f3a1
      DOCS_CNZZ_ID: 1280714941
      DOCS_CNZZ_WEB_ID: 1280714941
      NODE_VERSION: '16'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Handle yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn copy && yarn build

      - name: Build example site
        run: yarn example:build

      - name: Build documentation site
        run: yarn docs:build

      - name: Combine output
        run: |
          yarn cpx "example/.vuepress/dist/**" dist
          yarn cpx "docs/.vuepress/dist/**" dist/docs

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          repo: vuepress-star/vuepress-theme-star
          target_branch: gh-pages
          build_dir: dist
        env:
          GH_PAT: ${{ secrets.GH_PAGES_TOKEN }}
